import { NavigationItem } from '../models/navigation-item.model';

export const APP_NAVIGATION_ITEMS: readonly NavigationItem[] = [
  {
    id: 'inicio',
    label: 'Inicio',
    route: '/inicio',
    icon: 'home',
    order: 1,
    exact: false,
    visible: true,
  },
  {
    id: 'dashboard',
    label: 'Dashboard',
    route: '/dashboard',
    icon: 'dashboard',
    order: 2,
    exact: false,
    visible: true,
  },
  {
    id: 'campanas',
    label: 'Campañas',
    route: '/campanas',
    icon: 'campaign',
    order: 3,
    exact: false,
    visible: true,
  },
  {
    id: 'etiquetas',
    label: 'Etiquetas',
    route: '/etiquetas',
    icon: 'sell',
    order: 4,
    exact: false,
    visible: true,
  },
  {
    id: 'testeos',
    label: 'Testeos',
    route: '/testeos',
    icon: 'science',
    order: 5,
    exact: false,
    visible: true,
  },
  {
    id: 'conjuntos',
    label: 'Conjuntos',
    route: '/conjuntos',
    icon: 'inventory_2',
    order: 6,
    exact: false,
    visible: true,
  },
  {
    id: 'gastos',
    label: 'Gastos',
    route: '/gastos',
    icon: 'payments',
    order: 7,
    exact: false,
    visible: true,
  },
  {
    id: 'archivos',
    label: 'Archivos',
    route: '/archivos/importar',
    icon: 'folder',
    order: 8,
    exact: false,
    visible: true,
  },
  {
    id: 'integraciones',
    label: 'Integraciones',
    route: '/integraciones',
    icon: 'hub',
    order: 9,
    exact: false,
    visible: true,
  },
  {
    id: 'oficina',
    label: 'Oficina',
    route: '/oficina',
    icon: 'business_center',
    order: 10,
    exact: false,
    visible: true,
  },
  {
    id: 'torre-logistica',
    label: 'Torre Logística',
    route: '/torre-logistica',
    icon: 'local_shipping',
    order: 11,
    exact: false,
    visible: true,
  },
  {
    id: 'rastreo',
    label: 'Rastreo',
    route: '/rastreo',
    icon: 'conversion_path',
    order: 12,
    exact: false,
    visible: true,
  },
  {
    id: 'configuracion',
    label: 'Configuración',
    route: '/configuracion',
    icon: 'settings',
    order: 13,
    exact: false,
    visible: true,
  },
] as const;

export const ADMIN_NAVIGATION_ITEMS = APP_NAVIGATION_ITEMS;

export const LEGACY_ROUTE_REDIRECTS: readonly {
  readonly path: string;
  readonly redirectTo: string;
}[] = [
  { path: 'home', redirectTo: 'inicio' },
  { path: 'welcome', redirectTo: 'inicio' },
  { path: 'campaigns', redirectTo: 'campanas' },
  { path: 'tags', redirectTo: 'etiquetas' },
  { path: 'tags/:id', redirectTo: 'etiquetas/:id' },
  { path: 'labels', redirectTo: 'etiquetas' },
  { path: 'labels/:id', redirectTo: 'etiquetas/:id' },
  { path: 'testing', redirectTo: 'testeos' },
  { path: 'tests', redirectTo: 'testeos' },
  { path: 'experiments', redirectTo: 'testeos' },
  { path: 'experiments/:id', redirectTo: 'testeos/:id' },
  { path: 'ab-tests', redirectTo: 'testeos' },
  { path: 'product-groups', redirectTo: 'conjuntos' },
  { path: 'expenses', redirectTo: 'gastos' },
  { path: 'expenses/:id', redirectTo: 'gastos/:id' },
  { path: 'egresos', redirectTo: 'gastos' },
  { path: 'files', redirectTo: 'archivos' },
  { path: 'integrations', redirectTo: 'integraciones' },
  { path: 'office', redirectTo: 'oficina' },
  { path: 'logistics', redirectTo: 'torre-logistica' },
  { path: 'tracking', redirectTo: 'rastreo' },
  { path: 'tracking/:id', redirectTo: 'rastreo/pedido/:id' },
  { path: 'seguimiento', redirectTo: 'rastreo' },
  { path: 'settings', redirectTo: 'configuracion' },
  { path: 'profile', redirectTo: 'configuracion/perfil' },
  { path: 'daily-report', redirectTo: 'dashboard' },
  { path: 'orders', redirectTo: 'oficina' },
  { path: 'orders/:id', redirectTo: 'oficina/pedidos/:id' },
  { path: 'pedidos', redirectTo: 'oficina' },
  { path: 'pedidos/:id', redirectTo: 'oficina/pedidos/:id' },
  { path: 'products', redirectTo: 'conjuntos' },
  { path: 'inventory', redirectTo: 'conjuntos' },
  { path: 'deliveries', redirectTo: 'torre-logistica/entregas' },
  { path: 'returns', redirectTo: 'torre-logistica/devoluciones' },
  { path: 'shipping', redirectTo: 'torre-logistica' },
  { path: 'reports', redirectTo: 'dashboard' },
  { path: 'users', redirectTo: 'configuracion/usuarios' },
  { path: 'roles', redirectTo: 'configuracion/roles' },
  { path: 'permissions', redirectTo: 'configuracion/permisos' },
  { path: 'imports', redirectTo: 'archivos/importar' },
  { path: 'meta', redirectTo: 'campanas' },
  { path: 'statistics', redirectTo: 'dashboard' },
  { path: 'componentes/tabla', redirectTo: 'dashboard' },
] as const;
