import { PermissionCode } from '../../../core/services/permissions.service';
import { AdminRole, AdminUser, PersistedPermission } from './settings.models';

export const settingsFallbackPermissions: readonly PermissionCode[] = [
  'dashboard.read',
  'dashboard.write',
  'product-groups.read',
  'product-groups.create',
  'product-groups.update',
  'product-groups.delete',
  'product-groups.statistics',
  'products.read',
  'products.create',
  'products.update',
  'products.delete',
  'products.archive',
  'products.restore',
  'products.statistics',
  'products.profitability',
  'products.manage-pricing',
  'products.manage-costs',
  'products.manage-images',
  'products.manage-variants',
  'product-categories.read',
  'product-categories.manage',
  'product-brands.read',
  'product-brands.manage',
  'orders.read',
  'orders.create',
  'orders.update',
  'orders.delete',
  'orders.statistics',
  'tags.read',
  'tags.create',
  'tags.update',
  'tags.delete',
  'tags.archive',
  'tags.statistics',
  'testing.read',
  'testing.create',
  'testing.update',
  'testing.delete',
  'testing.archive',
  'testing.statistics',
  'campaigns.read',
  'campaigns.write',
  'reports.read',
  'reports.export',
  'files.import',
  'users.manage',
  'roles.manage',
  'settings.manage',
];

const adminPermissions = settingsFallbackPermissions;
const supervisorPermissions: readonly PermissionCode[] = [
  'dashboard.read',
  'orders.read',
  'orders.update',
  'orders.statistics',
  'product-groups.read',
  'products.read',
  'tags.read',
  'testing.read',
  'testing.statistics',
  'campaigns.read',
  'reports.read',
  'reports.export',
  'files.import',
];
const operatorPermissions: readonly PermissionCode[] = [
  'dashboard.read',
  'orders.read',
  'orders.update',
  'product-groups.read',
  'products.read',
  'tags.read',
  'files.import',
];
const analystPermissions: readonly PermissionCode[] = [
  'dashboard.read',
  'orders.read',
  'orders.statistics',
  'products.read',
  'products.statistics',
  'testing.read',
  'testing.statistics',
  'campaigns.read',
  'reports.read',
  'reports.export',
];

export const settingsFallbackRoles: readonly AdminRole[] = [
  {
    id: 'role-admin',
    name: 'Administrador',
    description: 'Control total del sistema y gestión de accesos.',
    permissions: adminPermissions,
    active: true,
    system: true,
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-21T12:00:00.000Z',
  },
  {
    id: 'role-supervisor',
    name: 'Supervisor',
    description: 'Supervisa operación, ventas, campañas y reportes.',
    permissions: supervisorPermissions,
    active: true,
    system: true,
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-20T16:30:00.000Z',
  },
  {
    id: 'role-operador',
    name: 'Operador',
    description: 'Gestiona pedidos, etiquetas y archivos operativos.',
    permissions: operatorPermissions,
    active: true,
    system: false,
    createdAt: '2026-08-02T09:00:00.000Z',
    updatedAt: '2026-08-19T14:25:00.000Z',
  },
  {
    id: 'role-analista',
    name: 'Analista',
    description: 'Consulta indicadores, pruebas, campañas y reportes.',
    permissions: analystPermissions,
    active: true,
    system: false,
    createdAt: '2026-08-03T10:00:00.000Z',
    updatedAt: '2026-08-18T11:15:00.000Z',
  },
];

export const settingsFallbackUsers: readonly AdminUser[] = [
  {
    id: 'settings-user-1',
    uid: 'settings-user-1',
    email: 'davidgarciaparada2020@gmail.com',
    username: 'david',
    firstName: 'David',
    lastName: 'Garcia',
    phone: '+573001112233',
    roleId: 'role-admin',
    permissions: adminPermissions,
    active: true,
    emailVerified: true,
    lastLogin: '2026-08-21T12:15:00.000Z',
  },
  {
    id: 'settings-user-2',
    uid: 'settings-user-2',
    email: 'operaciones@linkoba.com',
    username: 'operaciones',
    firstName: 'Laura',
    lastName: 'Mendez',
    phone: '+573105552020',
    roleId: 'role-supervisor',
    permissions: supervisorPermissions,
    active: true,
    emailVerified: true,
    lastLogin: '2026-08-21T10:20:00.000Z',
  },
  {
    id: 'settings-user-3',
    uid: 'settings-user-3',
    email: 'logistica@linkoba.com',
    username: 'logistica',
    firstName: 'Carlos',
    lastName: 'Rojas',
    phone: '+573207778888',
    roleId: 'role-operador',
    permissions: operatorPermissions,
    active: true,
    emailVerified: true,
    lastLogin: '2026-08-20T17:45:00.000Z',
  },
  {
    id: 'settings-user-4',
    uid: 'settings-user-4',
    email: 'analista@linkoba.com',
    username: 'analista',
    firstName: 'Natalia',
    lastName: 'Perez',
    phone: '+573156662222',
    roleId: 'role-analista',
    permissions: analystPermissions,
    active: false,
    emailVerified: true,
    lastLogin: undefined,
  },
];

export const settingsFallbackPersistedPermissions: readonly PersistedPermission[] = [];
