import { HomeQuickAccessItem } from '../data-access/home.models';

export const HOME_QUICK_ACCESS_ITEMS: readonly HomeQuickAccessItem[] = [
  {
    id: 'dashboard',
    title: 'Dashboard',
    description: 'Rendimiento general',
    actionLabel: 'Abrir',
    icon: 'dashboard',
    route: '/dashboard',
    permissions: ['dashboard.read'],
    order: 1,
  },
  {
    id: 'oficina',
    title: 'Oficina',
    description: 'Pedidos y operación',
    actionLabel: 'Abrir',
    icon: 'business_center',
    route: '/oficina',
    permissions: ['orders.read'],
    order: 2,
  },
  {
    id: 'campanas',
    title: 'Campañas',
    description: 'Pauta publicitaria',
    actionLabel: 'Abrir',
    icon: 'campaign',
    route: '/campanas',
    permissions: ['campaigns.read'],
    order: 3,
  },
  {
    id: 'torre-logistica',
    title: 'Torre Logística',
    description: 'Despachos e incidencias',
    actionLabel: 'Abrir',
    icon: 'local_shipping',
    route: '/torre-logistica',
    permissions: ['orders.read'],
    order: 4,
  },
  {
    id: 'gastos',
    title: 'Gastos',
    description: 'Soportes financieros',
    actionLabel: 'Abrir',
    icon: 'payments',
    route: '/gastos',
    permissions: ['reports.read'],
    order: 5,
  },
  {
    id: 'archivos',
    title: 'Archivos',
    description: 'Documentos privados',
    actionLabel: 'Abrir',
    icon: 'folder',
    route: '/archivos/importar',
    permissions: ['files.import'],
    order: 6,
  },
  {
    id: 'rastreo',
    title: 'Rastreo',
    description: 'Estado de envíos',
    actionLabel: 'Abrir',
    icon: 'conversion_path',
    route: '/rastreo',
    permissions: ['orders.read'],
    order: 7,
  },
  {
    id: 'conjuntos',
    title: 'Conjuntos',
    description: 'Grupos de productos',
    actionLabel: 'Abrir',
    icon: 'inventory_2',
    route: '/conjuntos',
    permissions: ['product-groups.read'],
    order: 8,
  },
  {
    id: 'testeos',
    title: 'Testeos',
    description: 'Experimentos activos',
    actionLabel: 'Abrir',
    icon: 'science',
    route: '/testeos',
    permissions: ['testing.read'],
    order: 9,
  },
  {
    id: 'etiquetas',
    title: 'Etiquetas',
    description: 'Clasificaciones',
    actionLabel: 'Abrir',
    icon: 'sell',
    route: '/etiquetas',
    permissions: ['tags.read'],
    order: 10,
  },
  {
    id: 'configuracion',
    title: 'Configuración',
    description: 'Usuarios y permisos',
    actionLabel: 'Abrir',
    icon: 'settings',
    route: '/configuracion',
    permissions: ['settings.manage', 'users.manage', 'roles.manage'],
    order: 11,
  },
] as const;
