import { ImportColumnDefinition } from '../models/import-column.model';
import { ImportStep } from '../models/import-process.model';
import { ImportType } from '../models/import-type.model';

export const FILE_IMPORT_HISTORY_KEY = 'ecommerce-control-center.files.import-history';
export const FILE_IMPORT_PREFERENCES_KEY = 'ecommerce-control-center.files.preferences';
export const MAX_IMPORT_FILE_SIZE = 15 * 1024 * 1024;
export const ACCEPTED_IMPORT_EXTENSIONS = ['xlsx', 'xls', 'csv'] as const;

export const IMPORT_STEPS: readonly ImportStep[] = [
  { id: 'file', label: 'Archivo' },
  { id: 'preview', label: 'Detección' },
  { id: 'mapping', label: 'Revisión' },
  { id: 'validation', label: 'Validación' },
  { id: 'confirmation', label: 'Confirmar' },
  { id: 'result', label: 'Resultado' },
];

export const ORDER_COLUMN_DEFINITIONS: readonly ImportColumnDefinition[] = [
  {
    key: 'orderNumber',
    label: 'Número de orden',
    description: 'Identificador único de la orden.',
    required: true,
    dataType: 'text',
    acceptedAliases: ['id', 'orden', 'pedido', 'id pedido', 'numero pedido', 'numero de pedido', 'nro pedido', 'codigo pedido', 'número orden', 'order', 'order id'],
    example: 'ORD-10293',
    unique: false,
    nullable: false,
    validatorIds: ['required'],
  },
  {
    key: 'date',
    label: 'Fecha',
    description: 'Fecha de creación de la orden.',
    required: true,
    dataType: 'date',
    acceptedAliases: ['fecha', 'fecha pedido', 'fecha de pedido', 'fecha creación', 'fecha creacion', 'fecha de la orden', 'fecha de reporte', 'created at'],
    example: '2026-07-29',
    unique: false,
    nullable: false,
    validatorIds: ['required', 'date'],
  },
  {
    key: 'customer',
    label: 'Cliente',
    description: 'Nombre del comprador.',
    required: true,
    dataType: 'text',
    acceptedAliases: ['cliente', 'nombre cliente', 'nombre del cliente', 'comprador', 'destinatario', 'nombre destinatario'],
    example: 'Laura Gómez',
    unique: false,
    nullable: false,
    validatorIds: ['required', 'minLength'],
  },
  {
    key: 'product',
    label: 'Producto',
    description: 'Producto asociado a la orden.',
    required: true,
    dataType: 'text',
    acceptedAliases: ['producto', 'nombre producto', 'producto principal', 'item', 'referencia', 'sku'],
    example: 'Helvor Shaper',
    unique: false,
    nullable: false,
    validatorIds: ['required'],
  },
  {
    key: 'city',
    label: 'Ciudad',
    description: 'Ciudad de destino.',
    required: true,
    dataType: 'text',
    acceptedAliases: ['ciudad', 'municipio', 'ciudad destino', 'destino', 'departamento ciudad'],
    example: 'Bogotá',
    unique: false,
    nullable: false,
    validatorIds: ['required'],
  },
  {
    key: 'status',
    label: 'Estado',
    description: 'Estado operativo de la orden.',
    required: true,
    dataType: 'status',
    acceptedAliases: ['estado', 'estatus', 'status', 'estado pedido', 'estado de la orden', 'estado guia', 'estado guia transportadora', 'estado despacho', 'estado envio'],
    example: 'Entregada',
    unique: false,
    nullable: false,
    validatorIds: ['required', 'status'],
  },
  {
    key: 'value',
    label: 'Valor',
    description: 'Valor total de la orden.',
    required: true,
    dataType: 'currency',
    acceptedAliases: ['valor', 'total', 'monto', 'venta', 'precio', 'precio total', 'valor total', 'total venta', 'total de la orden', 'recaudo'],
    example: '$ 125.000',
    unique: false,
    nullable: false,
    validatorIds: ['required', 'currency', 'positive'],
  },
  {
    key: 'carrier',
    label: 'Transportadora',
    description: 'Empresa encargada del envío.',
    required: false,
    dataType: 'text',
    acceptedAliases: ['transportadora', 'carrier', 'empresa transportadora', 'courier'],
    example: 'Envía',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'estimatedProfit',
    label: 'Ganancia',
    description: 'Ganancia estimada o reportada por la plataforma.',
    required: false,
    dataType: 'currency',
    acceptedAliases: ['ganancia', 'utilidad', 'profit', 'margen', 'ganancia estimada'],
    example: '$ 65.000',
    unique: false,
    nullable: true,
    validatorIds: ['currency'],
  },
  {
    key: 'phone',
    label: 'Teléfono',
    description: 'Teléfono del cliente.',
    required: false,
    dataType: 'phone',
    acceptedAliases: ['telefono', 'teléfono', 'celular', 'phone', 'telefono cliente', 'celular cliente'],
    example: '3001234567',
    unique: false,
    nullable: true,
    validatorIds: ['phone'],
  },
  {
    key: 'email',
    label: 'Correo',
    description: 'Correo del cliente.',
    required: false,
    dataType: 'email',
    acceptedAliases: ['correo', 'email', 'e-mail', 'correo cliente'],
    example: 'cliente@correo.com',
    unique: false,
    nullable: true,
    validatorIds: ['email'],
  },
  {
    key: 'customerDocumentType',
    label: 'Tipo de identificación',
    description: 'Tipo de identificación del cliente.',
    required: false,
    dataType: 'text',
    acceptedAliases: ['tipo de identificacion', 'tipo de identificación', 'tipo documento', 'tipo de documento'],
    example: 'CC',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'customerDocumentNumber',
    label: 'Identificación',
    description: 'Número de identificación del cliente.',
    required: false,
    dataType: 'text',
    acceptedAliases: ['nro de identificacion', 'nro de identificación', 'numero identificacion', 'número identificación', 'documento'],
    example: '1020304050',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'urgent',
    label: 'Urgente',
    description: 'Marca operativa de urgencia.',
    required: false,
    dataType: 'boolean',
    acceptedAliases: ['urgente', 'prioridad', 'urgent', 'novedad'],
    example: 'Sí',
    unique: false,
    nullable: true,
    defaultValue: false,
    validatorIds: ['boolean'],
  },
  {
    key: 'reportDate',
    label: 'Fecha de reporte',
    description: 'Fecha en la que Dropi generó el reporte.',
    required: false,
    dataType: 'date',
    acceptedAliases: ['fecha de reporte', 'fecha reporte'],
    example: '2026-08-04',
    unique: false,
    nullable: true,
    validatorIds: ['date'],
  },
  {
    key: 'orderHour',
    label: 'Hora',
    description: 'Hora de creación de la orden.',
    required: false,
    dataType: 'text',
    acceptedAliases: ['hora', 'hora pedido', 'hora de pedido'],
    example: '09:00',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'guideNumber',
    label: 'Guía',
    description: 'Número de guía de la transportadora.',
    required: false,
    dataType: 'text',
    acceptedAliases: ['numero guia', 'número guia', 'numero de guia', 'número de guía', 'guia', 'guía', 'guia transportadora'],
    example: '123456789',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'shippingType',
    label: 'Tipo de envío',
    description: 'Modalidad de envío reportada por Dropi.',
    required: false,
    dataType: 'text',
    acceptedAliases: ['tipo de envio', 'tipo de envío', 'modalidad envio', 'modalidad de envio'],
    example: 'Con recaudo',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'department',
    label: 'Departamento',
    description: 'Departamento de destino.',
    required: false,
    dataType: 'text',
    acceptedAliases: ['departamento destino', 'departamento', 'departamento de destino'],
    example: 'Antioquia',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'address',
    label: 'Dirección',
    description: 'Dirección de entrega.',
    required: false,
    dataType: 'text',
    acceptedAliases: ['direccion', 'dirección', 'direccion destino', 'dirección destino'],
    example: 'Calle 10 # 20-30',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'notes',
    label: 'Notas',
    description: 'Notas operativas del pedido.',
    required: false,
    dataType: 'text',
    acceptedAliases: ['notas', 'nota', 'observaciones pedido'],
    example: 'Entregar en portería',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'shippingCost',
    label: 'Flete',
    description: 'Costo de flete reportado.',
    required: false,
    dataType: 'currency',
    acceptedAliases: ['precio flete', 'flete', 'costo flete', 'valor flete'],
    example: '$ 12.000',
    unique: false,
    nullable: true,
    validatorIds: ['currency'],
  },
  {
    key: 'returnShippingCost',
    label: 'Flete devolución',
    description: 'Costo de devolución del flete.',
    required: false,
    dataType: 'currency',
    acceptedAliases: ['costo devolucion flete', 'costo devolución flete', 'flete devolucion', 'flete devolución'],
    example: '$ 8.000',
    unique: false,
    nullable: true,
    validatorIds: ['currency'],
  },
  {
    key: 'commission',
    label: 'Comisión',
    description: 'Comisión de la plataforma.',
    required: false,
    dataType: 'currency',
    acceptedAliases: ['comision', 'comisión'],
    example: '$ 3.500',
    unique: false,
    nullable: true,
    validatorIds: ['currency'],
  },
  {
    key: 'commissionPercentage',
    label: 'Porcentaje de comisión',
    description: 'Porcentaje de comisión de la plataforma.',
    required: false,
    dataType: 'percentage',
    acceptedAliases: ['% comision de la plataformma', '% comisión de la plataforma', 'porcentaje comision', 'porcentaje comisión'],
    example: '3,5 %',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'providerCost',
    label: 'Precio proveedor',
    description: 'Costo unitario del proveedor.',
    required: false,
    dataType: 'currency',
    acceptedAliases: ['precio proveedor', 'costo proveedor'],
    example: '$ 45.000',
    unique: false,
    nullable: true,
    validatorIds: ['currency'],
  },
  {
    key: 'providerCostTotal',
    label: 'Costo proveedor total',
    description: 'Costo total de proveedor por cantidad.',
    required: false,
    dataType: 'currency',
    acceptedAliases: ['precio proveedor x cantidad', 'costo proveedor total', 'precio proveedor total'],
    example: '$ 90.000',
    unique: false,
    nullable: true,
    validatorIds: ['currency'],
  },
  {
    key: 'productId',
    label: 'Producto ID',
    description: 'Identificador del producto en Dropi.',
    required: false,
    dataType: 'text',
    acceptedAliases: ['producto id', 'id producto'],
    example: '1234',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'sku',
    label: 'SKU',
    description: 'SKU del producto.',
    required: false,
    dataType: 'text',
    acceptedAliases: ['sku', 'referencia sku'],
    example: 'HEL-001',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'variationId',
    label: 'Variación ID',
    description: 'Identificador de variación.',
    required: false,
    dataType: 'text',
    acceptedAliases: ['variacion id', 'variación id', 'id variacion', 'id variación'],
    example: 'VAR-1',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'variation',
    label: 'Variación',
    description: 'Variación del producto.',
    required: false,
    dataType: 'text',
    acceptedAliases: ['variacion', 'variación'],
    example: 'Negro / M',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'quantity',
    label: 'Cantidad',
    description: 'Cantidad de unidades vendidas.',
    required: false,
    dataType: 'number',
    acceptedAliases: ['cantidad', 'unidades'],
    example: '2',
    unique: false,
    nullable: true,
    validatorIds: ['positive'],
  },
  {
    key: 'novelty',
    label: 'Novedad',
    description: 'Novedad reportada por la transportadora.',
    required: false,
    dataType: 'text',
    acceptedAliases: ['novedad', 'motivo novedad'],
    example: 'Dirección incompleta',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'noveltySolved',
    label: 'Novedad solucionada',
    description: 'Indica si la novedad fue solucionada.',
    required: false,
    dataType: 'boolean',
    acceptedAliases: ['fue solucionada la novedad', 'novedad solucionada', 'solucionada'],
    example: 'Sí',
    unique: false,
    nullable: true,
    validatorIds: ['boolean'],
  },
  {
    key: 'noveltyHour',
    label: 'Hora de novedad',
    description: 'Hora de registro de la novedad.',
    required: false,
    dataType: 'text',
    acceptedAliases: ['hora de novedad'],
    example: '15:20',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'noveltyDate',
    label: 'Fecha de novedad',
    description: 'Fecha de registro de la novedad.',
    required: false,
    dataType: 'date',
    acceptedAliases: ['fecha de novedad'],
    example: '2026-07-29',
    unique: false,
    nullable: true,
    validatorIds: ['date'],
  },
  {
    key: 'solution',
    label: 'Solución',
    description: 'Solución aplicada a la novedad.',
    required: false,
    dataType: 'text',
    acceptedAliases: ['solucion', 'solución'],
    example: 'Cliente confirmó dirección',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'solvedHour',
    label: 'Hora de solución',
    description: 'Hora en la que se solucionó la novedad.',
    required: false,
    dataType: 'text',
    acceptedAliases: ['hora de solucion', 'hora de solución'],
    example: '16:10',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'solvedDate',
    label: 'Fecha de solución',
    description: 'Fecha en la que se solucionó la novedad.',
    required: false,
    dataType: 'date',
    acceptedAliases: ['fecha de solucion', 'fecha de solución'],
    example: '2026-07-29',
    unique: false,
    nullable: true,
    validatorIds: ['date'],
  },
  {
    key: 'observation',
    label: 'Observación',
    description: 'Observación operativa.',
    required: false,
    dataType: 'text',
    acceptedAliases: ['observacion', 'observación'],
    example: 'Sin novedad adicional',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'lastMovementHour',
    label: 'Hora de último movimiento',
    description: 'Hora del último movimiento logístico.',
    required: false,
    dataType: 'text',
    acceptedAliases: ['hora de ultimo movimiento', 'hora de último movimiento'],
    example: '10:40',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'lastMovementDate',
    label: 'Fecha de último movimiento',
    description: 'Fecha del último movimiento logístico.',
    required: false,
    dataType: 'date',
    acceptedAliases: ['fecha de ultimo movimiento', 'fecha de último movimiento'],
    example: '2026-07-30',
    unique: false,
    nullable: true,
    validatorIds: ['date'],
  },
  {
    key: 'lastMovement',
    label: 'Último movimiento',
    description: 'Último movimiento logístico reportado.',
    required: false,
    dataType: 'text',
    acceptedAliases: ['ultimo movimiento', 'último movimiento'],
    example: 'En reparto',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'lastMovementConcept',
    label: 'Concepto último movimiento',
    description: 'Concepto asociado al último movimiento.',
    required: false,
    dataType: 'text',
    acceptedAliases: ['concepto ultimo movimiento', 'concepto último movimiento'],
    example: 'Novedad en entrega',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'lastMovementLocation',
    label: 'Ubicación último movimiento',
    description: 'Ubicación del último movimiento logístico.',
    required: false,
    dataType: 'text',
    acceptedAliases: ['ubicacion de ultimo movimiento', 'ubicación de último movimiento'],
    example: 'Bogotá',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'seller',
    label: 'Vendedor',
    description: 'Vendedor asociado.',
    required: false,
    dataType: 'text',
    acceptedAliases: ['vendedor'],
    example: 'Equipo comercial',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'storeType',
    label: 'Tipo de tienda',
    description: 'Tipo de tienda de origen.',
    required: false,
    dataType: 'text',
    acceptedAliases: ['tipo de tienda'],
    example: 'Shopify',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'storeName',
    label: 'Tienda',
    description: 'Tienda de origen.',
    required: false,
    dataType: 'text',
    acceptedAliases: ['tienda'],
    example: 'Tienda principal',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'storeOrderId',
    label: 'ID orden tienda',
    description: 'ID de la orden en la tienda.',
    required: false,
    dataType: 'text',
    acceptedAliases: ['id de orden de tienda', 'id orden tienda'],
    example: '10001',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'storeOrderNumber',
    label: 'Número pedido tienda',
    description: 'Número de pedido en la tienda.',
    required: false,
    dataType: 'text',
    acceptedAliases: ['numero de pedido de tienda', 'número de pedido de tienda', 'pedido tienda'],
    example: 'PED-10001',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'tags',
    label: 'Tags',
    description: 'Etiquetas operativas.',
    required: false,
    dataType: 'text',
    acceptedAliases: ['tags', 'etiquetas'],
    example: 'vip, mayorista',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'guideGeneratedAt',
    label: 'Fecha guía generada',
    description: 'Fecha de generación de la guía.',
    required: false,
    dataType: 'date',
    acceptedAliases: ['fecha guia generada', 'fecha guía generada'],
    example: '2026-07-29',
    unique: false,
    nullable: true,
    validatorIds: ['date'],
  },
  {
    key: 'indemnizationCount',
    label: 'Indemnizaciones',
    description: 'Contador de indemnizaciones.',
    required: false,
    dataType: 'number',
    acceptedAliases: ['contador de indemnizaciones'],
    example: '0',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
  {
    key: 'lastIndemnizationConcept',
    label: 'Última indemnización',
    description: 'Concepto de la última indemnización.',
    required: false,
    dataType: 'text',
    acceptedAliases: ['concepto ultima indenmización', 'concepto última indemnización', 'concepto ultima indemnizacion'],
    example: 'Sin indemnización',
    unique: false,
    nullable: true,
    validatorIds: [],
  },
];

const basicColumns = ['Nombre', 'Fecha', 'Valor', 'Estado'];

export const IMPORT_TYPES: readonly ImportType[] = [
  {
    id: 'orders',
    name: 'Órdenes',
    description: 'Pedidos recibidos desde canales ecommerce.',
    icon: 'receipt_long',
    acceptedExtensions: ACCEPTED_IMPORT_EXTENSIONS,
    requiredColumns: ORDER_COLUMN_DEFINITIONS.filter((column) => column.required).map(
      (column) => column.label,
    ),
    optionalColumns: ORDER_COLUMN_DEFINITIONS.filter((column) => !column.required).map(
      (column) => column.label,
    ),
    maximumFileSize: MAX_IMPORT_FILE_SIZE,
    supportsMultipleSheets: true,
    templateId: 'orders-template',
    enabled: true,
  },
  ...[
    ['deliveries', 'Entregas', 'Entregas reportadas por transportadora.', 'local_shipping'],
    ['returns', 'Devoluciones', 'Casos devueltos o rechazados.', 'assignment_return'],
    ['expenses', 'Gastos', 'Costos operativos y administrativos.', 'payments'],
    ['campaigns', 'Campañas publicitarias', 'Métricas de pauta y campañas.', 'campaign'],
    ['products', 'Productos', 'Catálogo operativo de productos.', 'inventory_2'],
    ['product-groups', 'Conjuntos de productos', 'Agrupaciones comerciales.', 'category'],
    ['inventory', 'Inventario', 'Existencias y movimientos.', 'warehouse'],
    ['collections', 'Recaudos', 'Pagos y recaudos confirmados.', 'account_balance_wallet'],
  ].map(
    ([id, name, description, icon]) =>
      ({
        id,
        name,
        description,
        icon,
        acceptedExtensions: ACCEPTED_IMPORT_EXTENSIONS,
        requiredColumns: basicColumns,
        optionalColumns: ['Observaciones', 'Responsable'],
        maximumFileSize: MAX_IMPORT_FILE_SIZE,
        supportsMultipleSheets: true,
        templateId: `${id}-template`,
        enabled: true,
      }) as ImportType,
  ),
];

export const ALLOWED_ORDER_STATUSES = [
  'Pendiente',
  'Confirmada',
  'En preparación',
  'Despachada',
  'En tránsito',
  'Entregada',
  'Devuelta',
  'Cancelada',
  'CANCELADO',
  'DEVOLUCION',
  'ENTREGADO',
  'INTENTO DE ENTREGA',
  'PENDIENTE CONFIRMACION',
  'RECLAME EN OFICINA',
  'RECHAZADO',
  'DESPACHADO',
  'EN BODEGA',
  'EN BODEGA ORIGEN',
  'TRANSITO NACIONAL',
  'NOVEDAD',
] as const;


