import { LogisticsOrder } from './logistics.models';

export const logisticsOrderFixture: LogisticsOrder = {
  id: 'order-1',
  orderNumber: 'ORD-2026-0001',
  customerId: 'customer-1',
  customerName: 'Laura Gomez',
  customerPhone: '+573001112233',
  customerEmail: 'laura@example.com',
  city: 'Bogota',
  department: 'Cundinamarca',
  address: 'Calle 100 # 15-20',
  productId: 'product-1',
  productName: 'Kit Premium',
  productGroupId: 'group-1',
  productGroupName: 'Helvor 2',
  quantity: 1,
  subtotal: 119900,
  shippingCost: 12000,
  discount: 0,
  total: 131900,
  currency: 'COP',
  paymentMethod: 'Cash on Delivery',
  paymentStatus: 'Pending',
  orderStatus: 'Confirmed',
  deliveryStatus: 'Pending',
  carrier: 'Coordinadora',
  trackingNumber: '',
  observations: 'Cliente pide llamada en la tarde.',
  urgent: true,
  source: 'Manual',
  createdBy: 'admin',
  createdAt: '2026-07-29T10:00:00.000Z',
  updatedAt: '2026-07-29T11:00:00.000Z',
};
